# Generated by Django 4.1.2 on 2022-12-16 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='RefRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='company name')),
                ('company_slug', models.SlugField(blank=True, max_length=150, null=True, verbose_name='company_slug')),
                ('date_from', models.DateField(verbose_name='date from')),
                ('date_to', models.DateField(verbose_name='date to')),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='to email')),
                ('status', models.CharField(choices=[('UNIN', 'Uninitiated'), ('PEND', 'Pending'), ('COMP', 'Complete')], default='UNIN', max_length=4, verbose_name='status')),
                ('time_sent', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time_sent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Reference request',
                'verbose_name_plural': 'Reference requests',
            },
        ),
        migrations.CreateModel(
            name='RefResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last name')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='company name')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('relation', models.CharField(choices=[('BOSS', 'I was a manager'), ('COLL', ' I was a colleague'), ('CONS', 'he/she was temporary consultant'), ('OTH', 'Other')], default='BOSS', max_length=4, verbose_name='relation to referee')),
                ('other_relation', models.CharField(blank=True, max_length=80, null=True, verbose_name='if "Other", please specify')),
                ('main_tasks', models.TextField(verbose_name='describe main tasks')),
                ('elaborate', models.TextField(verbose_name='elaborate')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='extra')),
                ('email', models.EmailField(max_length=254, verbose_name='your email')),
                ('referee_first_name', models.CharField(max_length=50, verbose_name='referee first name')),
                ('referee_last_name', models.CharField(max_length=50, verbose_name='referee last name')),
                ('completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('time_added', models.DateTimeField(auto_now=True, verbose_name='time added')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile', verbose_name='profile')),
                ('ref_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.refrequest', verbose_name='request to')),
            ],
            options={
                'verbose_name': 'Reference response',
                'verbose_name_plural': 'Reference responses',
                'ordering': ['ref_request'],
            },
        ),
    ]
