# Generated by Django 4.1.2 on 2022-11-12 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="last name"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_from",
                    partial_date.fields.PartialDateField(verbose_name="date from"),
                ),
                (
                    "date_to",
                    partial_date.fields.PartialDateField(verbose_name="date to"),
                ),
                (
                    "to_email",
                    models.EmailField(max_length=254, verbose_name="to email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNIN", "Uninitiated"),
                            ("PEND", "Pending"),
                            ("COMP", "Complete"),
                        ],
                        default="UNIN",
                        max_length=4,
                        verbose_name="",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.profile",
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference request",
                "verbose_name_plural": "Reference requests",
            },
        ),
    ]
