# Generated by Django 4.1.2 on 2022-11-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_refrequest_company_name_refrequest_time_sent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refresponse",
            options={
                "verbose_name": "Reference response",
                "verbose_name_plural": "Reference responses",
            },
        ),
        migrations.AlterField(
            model_name="refresponse",
            name="other_relation",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name="if Other, please specify",
            ),
        ),
    ]
