# Generated by Django 4.1.2 on 2022-11-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_refresponse_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refresponse",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.profile",
                verbose_name="profile",
            ),
        ),
    ]
