# Generated by Django 4.1.2 on 2022-12-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_alter_refresponse_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refresponse",
            options={
                "ordering": ["ref_request"],
                "verbose_name": "Reference response",
                "verbose_name_plural": "Reference responses",
            },
        ),
        migrations.AlterField(
            model_name="refresponse",
            name="ref_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.refrequest",
                verbose_name="request to",
            ),
        ),
    ]
