# Generated by Django 4.1.2 on 2022-12-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_alter_refresponse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refresponse",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="is completed"),
        ),
    ]
