# Generated by Django 4.1.2 on 2022-12-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_refresponse_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="refrequest",
            name="company_slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, verbose_name="company_slug"
            ),
        ),
    ]
