# Generated by Django 4.1.2 on 2022-12-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_refrequest_company_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refrequest",
            name="date_from",
            field=models.DateTimeField(verbose_name="date from"),
        ),
        migrations.AlterField(
            model_name="refrequest",
            name="date_to",
            field=models.DateTimeField(verbose_name="date to"),
        ),
        migrations.AlterField(
            model_name="refresponse",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="your email"),
        ),
        migrations.AlterField(
            model_name="refresponse",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="first_name"
            ),
        ),
        migrations.AlterField(
            model_name="refresponse",
            name="other_relation",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name='if "Other", please specify',
            ),
        ),
        migrations.AlterField(
            model_name="refresponse",
            name="relation",
            field=models.CharField(
                choices=[
                    ("BOSS", "I was a manager"),
                    ("COLL", " I was a colleague"),
                    ("CONS", "he/she was temporary consultant"),
                    ("OTH", "Other"),
                ],
                default="BOSS",
                max_length=4,
                verbose_name="relation to referee",
            ),
        ),
    ]
