# Generated by Django 4.1.2 on 2022-12-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0009_alter_refrequest_date_from_alter_refrequest_date_to_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="refrequest",
            name="date_from",
            field=models.DateField(verbose_name="date from"),
        ),
        migrations.AlterField(
            model_name="refrequest",
            name="date_to",
            field=models.DateField(verbose_name="date to"),
        ),
    ]
