# Generated by Django 4.1.2 on 2022-12-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_alter_refrequest_date_from_alter_refrequest_date_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refresponse",
            name="extra",
            field=models.TextField(blank=True, null=True, verbose_name="extra"),
        ),
    ]
